version: "3"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      # - ./mongo-db:/data/db
      - "mongo_data:/data/db"
  zoofi-translation-cms:
    image: zoofy-translations
    ports:
      - "1337:1337"
    environment:
      DATABASE_HOST: mongo
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root

volumes:
  mongo_data:
